# name of the software
name: Informationgrid

# use for local testing
# baseurl: /github-pages
baseurl:

# versions of the software (current is first)
versions:
  - latest (6.2.0)
  - 6.1.0
  - 6.0.0
  - 5.14.0
  - 5.13.0
  - 5.12.0
  - 5.11.0
  - 5.10.0
  - 5.9.0
  - 5.8.0
  - 5.7.0
  - 5.6.0
  - 5.5.0
  - 5.4.0
  - 5.3.0
  - 5.2.0
  - 5.1.0
  - 5.0.0

# licence of the software
license: EUPL V1.1
licenseUrl: https://joinup.ec.europa.eu/software/page/eupl

# list of additional links on the right of the top menu
headerLinks:
  - title: GitHub
    url: https://github.com/informationgrid/informationgrid.github.io

# list of additional links on the footer
footerLinks:
  - title: GitHub
    url: https://github.com/informationgrid/informationgrid.github.io
  - title: Impressum
    url: about/disclaimer.html

gems:
  - jekyll-redirect-from
  - jekyll-sitemap

# DON'T MODIFY
highlighter: rouge

exclude: ['README.md', 'Gemfile.lock', 'Gemfile']
