# name of the software
name: Informationgrid

# use for local testing
# baseurl: /github-pages
baseurl:


# versions of the software (current is first)
versions:
  - latest (5.1.0)
  - 5.0.0
  - 4.6.0
  - 4.5.0
  - 4.4.0
  - 4.3.0
  - 4.2.0
  - 4.1.0
  - 4.0.0
  - 3.6.2

# licence of the software
license: EUPL V1.1
licenseUrl: https://joinup.ec.europa.eu/software/page/eupl

# list of additional links on the right of the top menu
headerLinks:
  - title: GitHub
    url: https://github.com/informationgrid/informationgrid.github.io

# list of additional links on the footer
footerLinks:
  - title: GitHub
    url: https://github.com/informationgrid/informationgrid.github.io
  - title: Impressum
    url: about/disclaimer.html

gems:
  - jekyll-redirect-from
  - jekyll-sitemap

# DON'T MODIFY
highlighter: rouge

exclude: ['README.md', 'Gemfile.lock', 'Gemfile']
