# name of the software
name: Informationgrid

# use for local testing
# baseurl: /github-pages
baseurl:


# versions of the software (current is first)
versions:
  - 3.6.1
  - 3.6.0
  - 3.5
  - 3.4

# licence of the software
license: EUPL V1.1
licenseUrl: https://joinup.ec.europa.eu/software/page/eupl

# list of additional links on the right of the top menu
headerLinks:
  - title: GitHub
    url: https://github.com/informationgrid/informationgrid.github.io

# list of additional links on the footer
footerLinks:
  - title: GitHub
    url: https://github.com/informationgrid/informationgrid.github.io
  - title: Issues
    url: https://github.com/informationgrid/docs/issues?state=open
  - title: Impressum
    url: about/disclaimer.html

gems:
  - jekyll-redirect-from
  - jekyll-sitemap

# DON'T MODIFY
highlighter: rouge

exclude: ['README.md', 'Gemfile.lock', 'Gemfile']
